import os
from instagrapi import Client
from dotenv import load_dotenv

load_dotenv()

class Publisher:
    def __init__(self, session_file="session.json"):
        self.cl = Client()
        self.session_file = session_file
        self.user = os.getenv("IG_USER")
        self.password = os.getenv("IG_PASS")

    def login(self):
        if os.path.exists(self.session_file):
            print(f"Loading session from {self.session_file}")
            self.cl.load_settings(self.session_file)
            try:
                self.cl.login(self.user, self.password)
            except Exception as e:
                print(f"Session login failed: {e}")
                self.cl.login(self.user, self.password)
        else:
            print(f"No session found, logging in for the first time.")
            self.cl.login(self.user, self.password)
            self.cl.dump_settings(self.session_file)
            print(f"Session saved to {self.session_file}")
        return True

    def upload_photo(self, path, caption="Check out this meme! #ai #meme"):
        print(f"Uploading {path} to Instagram...")
        media = self.cl.photo_upload(path, caption)
        print(f"Uploaded successfully! ID: {media.pk}")
        return media.pk

if __name__ == "__main__":
    p = Publisher()
    # p.login()
    # p.upload_photo("meme.png", "A funny meme about AI generated by AI!")
